# PIPELINE DEFINITION
# Name: banknote-authentication-training-pipeline
# Description: Building the pipeline
# Inputs:
#    data_bucket: str
#    model_bucket_metadata: str
#    model_repo: str
#    project_id: str
components:
  comp-compare-model:
    executorLabel: exec-compare-model
    inputDefinitions:
      artifacts:
        new_model:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
      parameters:
        model_bucket_metadata:
          parameterType: STRING
    outputDefinitions:
      parameters:
        Output:
          parameterType: STRING
  comp-condition-1:
    dag:
      tasks:
        upload-model-to-gcs:
          cachingOptions:
            enableCache: true
          componentRef:
            name: comp-upload-model-to-gcs
          inputs:
            artifacts:
              model:
                componentInputArtifact: pipelinechannel--train-model-output_model
            parameters:
              model_repo:
                componentInputParameter: pipelinechannel--model_repo
              project_id:
                componentInputParameter: pipelinechannel--project_id
          taskInfo:
            name: upload-model-to-gcs
    inputDefinitions:
      artifacts:
        pipelinechannel--train-model-output_model:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
      parameters:
        pipelinechannel--compare-model-Output:
          parameterType: STRING
        pipelinechannel--model_repo:
          parameterType: STRING
        pipelinechannel--project_id:
          parameterType: STRING
  comp-train-model:
    executorLabel: exec-train-model
    inputDefinitions:
      parameters:
        data_bucket:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        output_model:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
  comp-upload-model-to-gcs:
    executorLabel: exec-upload-model-to-gcs
    inputDefinitions:
      artifacts:
        model:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
      parameters:
        model_repo:
          parameterType: STRING
        project_id:
          parameterType: STRING
    outputDefinitions:
      parameters:
        Output:
          parameterType: STRING
deploymentSpec:
  executors:
    exec-compare-model:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - compare_model
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'google-cloud-storage'\
          \  &&  python3 -m pip install --quiet --no-warn-script-location 'kfp==2.14.6'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef compare_model(new_model: Input[Model], model_bucket_metadata:\
          \ str) -> str:\n    \"\"\"\n    Function compares local model to existing\
          \ one in model bucket\n    :returns: \"NEW\" if accuracy of the new model\
          \ is better, \"EXISTING\" if the old one is better.\n    \"\"\"\n    import\
          \ json, tempfile, os\n    from google.cloud import storage\n\n    # Get\
          \ new model accuracy\n    new_accuracy = float(new_model.metadata.get(\"\
          accuracy\", 0))\n\n    # Get old model accuracy\n    bucket_name, blob_path\
          \ = model_bucket_metadata.replace(\"gs://\", \"\").split(\"/\", 1)\n   \
          \ client = storage.Client()\n    bucket = client.bucket(bucket_name)\n \
          \   blob = bucket.blob(blob_path)\n\n    # Temporarily download the older\
          \ model from the model bucket\n    tmp = tempfile.NamedTemporaryFile(delete=False)\n\
          \    blob.download_to_filename(tmp.name)\n    with open(tmp.name, \"r\"\
          ) as f:\n        old_metadata = json.load(f)\n\n    old_accuracy = float(old_metadata[\"\
          accuracy\"])\n\n    os.remove(tmp.name)\n    # Check whether the new model\
          \ outperforms the old one\n    decision = \"NEW\" if new_accuracy > old_accuracy\
          \ else \"EXISTING\"\n    return decision\n\n"
        image: python:3.10.7-slim
    exec-train-model:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - train_model
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'pandas' 'tensorflow'\
          \ 'scikit-learn' 'fsspec' 'gcsfs'  &&  python3 -m pip install --quiet --no-warn-script-location\
          \ 'kfp==2.14.6' '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"\
          3.9\"' && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef train_model(data_bucket:str, output_model: Output[Model]):\n\
          \    \"\"\"\n    Function takes data file from the data bucket and trains\
          \ a simple MLP model on it.\n    \"\"\"\n    import random\n    import pandas\
          \ as pd\n    from tensorflow import keras\n    from sklearn.model_selection\
          \ import train_test_split\n    random.seed(67)\n\n    # 1. Load dataset\
          \ from data bucket\n    #url = \"https://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt\"\
          \n    cols = [\"variance\", \"skewness\", \"curtosis\", \"entropy\", \"\
          class\"]\n    #df = pd.read_csv(url, header=None, names=cols)\n\n    df\
          \ = pd.read_csv(f\"gs://{data_bucket}/data_banknote_authentication.txt\"\
          , header=None, names=cols)\n\n    X = df[[\"variance\", \"skewness\", \"\
          curtosis\", \"entropy\"]].values\n    y = df[\"class\"].values\n\n    #\
          \ 2. Split data\n    X_train, X_test, y_train, y_test = train_test_split(X,\
          \ y, test_size=0.2, random_state=42)\n\n    # 3. Normalize inside the model\
          \ (so we don\u2019t need a separate scaler)\n    normalizer = keras.layers.Normalization()\n\
          \    normalizer.adapt(X_train)\n\n    # 4. Build simple MLP model\n    model\
          \ = keras.Sequential([\n        normalizer,\n        keras.layers.Dense(8,\
          \ activation=\"relu\"),\n        keras.layers.Dense(4, activation=\"relu\"\
          ),\n        keras.layers.Dense(1, activation=\"sigmoid\")\n    ])\n\n  \
          \  model.compile(optimizer=\"adam\", loss=\"binary_crossentropy\", metrics=[\"\
          accuracy\"])\n\n    # 5. Train model\n    model.fit(X_train, y_train, epochs=15,\
          \ batch_size=8, validation_split=0.2, verbose=1)\n\n    # 6. Evaluate model\n\
          \    loss, acc = model.evaluate(X_test, y_test, verbose=0)\n    print(f\"\
          \ Test accuracy: {acc:.3f}\")\n\n    # 7. Save model in the same folder\n\
          \    model.save(output_model.path + \".keras\")\n\n    # 8. Add metadata\n\
          \    metadata = {\n        \"accuracy\": acc,\n        \"algo\": \"MLP\"\
          ,\n        \"file_type\": \".keras\"\n    }\n\n    # 9. Attach metadata\
          \ to Vertex artifact (for pipelines)\n    output_model.metadata.update(metadata)\n\
          \n"
        image: python:3.10.7-slim
    exec-upload-model-to-gcs:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - upload_model_to_gcs
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'google-cloud-storage'\
          \  &&  python3 -m pip install --quiet --no-warn-script-location 'kfp==2.14.6'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef upload_model_to_gcs(project_id: str, model_repo: str, model:\
          \ Input[Model])->str:\n    \"\"\"\n    Function uploads model and metadata\
          \ .json\n    \"\"\"\n    from google.cloud import storage\n    from urllib.parse\
          \ import urlparse\n    import json\n    import os\n    import tempfile\n\
          \n\n    # parse gs://...\n    p = urlparse(model_repo) if model_repo.startswith(\"\
          gs://\") else None\n    bucket_name = (p.netloc if p else model_repo.split(\"\
          /\",1)[0])\n    prefix = (p.path.lstrip(\"/\") if p else (model_repo.split(\"\
          /\",1)[1] if \"/\" in model_repo else \"\"))\n\n    client = storage.Client(project=project_id)\n\
          \    bucket = client.bucket(bucket_name)\n\n    # model path from artifact\n\
          \    ext = str(model.metadata.get(\"file_type\", \".keras\"))\n    algo\
          \ = str(model.metadata.get(\"algo\", \"model\"))\n    src_model = model.path\
          \ + ext\n    dst_model = \"/\".join(filter(None, [prefix, f\"{algo}_model{ext}\"\
          ]))\n    bucket.blob(dst_model).upload_from_filename(src_model)\n\n    #\
          \ create & upload metadata json from artifact metadata\n    meta = dict(model.metadata)\n\
          \    with tempfile.NamedTemporaryFile(\"w\", delete=False) as f:\n     \
          \   json.dump(meta, f, indent=4)\n        tmp_meta = f.name\n    dst_meta\
          \ = \"/\".join(filter(None, [prefix, \"model_metadata.json\"]))\n    bucket.blob(dst_meta).upload_from_filename(tmp_meta)\n\
          \n    return f\"gs://{bucket_name}/{dst_model}\"\n\n"
        image: python:3.10.7-slim
pipelineInfo:
  description: Building the pipeline
  name: banknote-authentication-training-pipeline
root:
  dag:
    tasks:
      compare-model:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-compare-model
        dependentTasks:
        - train-model
        inputs:
          artifacts:
            new_model:
              taskOutputArtifact:
                outputArtifactKey: output_model
                producerTask: train-model
          parameters:
            model_bucket_metadata:
              componentInputParameter: model_bucket_metadata
        taskInfo:
          name: compare-model
      condition-1:
        componentRef:
          name: comp-condition-1
        dependentTasks:
        - compare-model
        - train-model
        inputs:
          artifacts:
            pipelinechannel--train-model-output_model:
              taskOutputArtifact:
                outputArtifactKey: output_model
                producerTask: train-model
          parameters:
            pipelinechannel--compare-model-Output:
              taskOutputParameter:
                outputParameterKey: Output
                producerTask: compare-model
            pipelinechannel--model_repo:
              componentInputParameter: model_repo
            pipelinechannel--project_id:
              componentInputParameter: project_id
        taskInfo:
          name: condition-1
        triggerPolicy:
          condition: inputs.parameter_values['pipelinechannel--compare-model-Output']
            == 'NEW'
      train-model:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train-model
        inputs:
          parameters:
            data_bucket:
              componentInputParameter: data_bucket
        taskInfo:
          name: train-model
  inputDefinitions:
    parameters:
      data_bucket:
        parameterType: STRING
      model_bucket_metadata:
        parameterType: STRING
      model_repo:
        parameterType: STRING
      project_id:
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.14.6
